clear all
close all
clc

%Variabile
A=1; %v
f=100; %hz
tip=1; %tipul de semnal
R1=10; %Kohm
R2=10;
Eplus=5;
Eminus=-5;%V

%Generare Fereastra
Fig=figure('Name','Amplificator inversor cu AO',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.8 0.7], 'color','#D9D9D9');

%Imagine
x= imread ('poza1.png');
subplot('position', [.35 .6 .3 .27]);
image(x)
axis off;

%Grup
RadioGroup=uibuttongroup('Visible','on',...
    'BackgroundColor','#CDCDCD',...
    'ForegroundColor','black',...
    'Title','Setari:',...
    'FontSize',12,...
    'TitlePosition','centertop',...
    'Tag','radiobutton',...
    'Position',[0.05 0.05 0.9 0.3]);

%popup
Slider=uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.4 0.2 0.2 0.1],...
    'FontSize',12,... 
    'String','Sinus|Dreptunghi',...
    'Value',tip,...
    'Callback','tip = get(gco,''Value''); afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);');
TextSlider=uicontrol('Style','text',... 
    'Units','normalized',... 
    'Position',[0.3 0.2 0.1 0.1],...
    'FontSize',12,... 
    'backgroundcolor','#CDCDCD',... 
    'foregroundcolor','black',... 
    'String','Tip semnal:');


%Vi
Amplitudine=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.2 0.2 0.05 0.05],...
    'FontSize',12,... 
    'backgroundcolor','#CDCDCD',... 
    'String',num2str(A),...
    'Callback','A = str2num(get(Amplitudine,''String'')); afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);');
TextVi=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.1 0.19 0.1 0.05],...
    'FontSize',12,... 
    'backgroundcolor','#CDCDCD',...
    'foregroundcolor','black',...
    'String','Amplitudine [V]');

%F
Frecventa=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.2 0.1 0.05 0.05],...
    'FontSize',12,... 
    'backgroundcolor','#CDCDCD',... 
    'String',num2str(f),...
    'Callback','f = str2num(get(Frecventa,''String'')); afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);');
TextF=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.1 0.11 0.1 0.03],...
    'FontSize',12,... 
    'backgroundcolor','#CDCDCD',... 
    'foregroundcolor','black',...
    'String','Frecventa [Hz]');

%R1
Rezistenta1=uicontrol('Style','slide',...
            'Units','normalized',...
            'Position',[0.75 0.2 .18 .03],...
            'Min',1,'Max',100,'Value',R1,...
            'Callback','R1 = get(Rezistenta1,''Value''); afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);');
TextR1=uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.7 0.183 0.05 0.05],...
        'FontSize',12,... 
        'backgroundcolor','#CDCDCD',... 
        'foregroundcolor','black',...
        'String','R1');

%R2
Rezistenta2=uicontrol('Style','slide',...
            'Units','normalized',...
            'Position',[0.75 0.1 .18 .03],...
            'Min',1,'Max',100,'Value',R1,...
            'Callback','R2 = get(Rezistenta2,''Value''); afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);');
TextR2=uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.7 0.083 0.05 0.05],...
        'FontSize',12,... 
        'backgroundcolor','#CDCDCD',... 
        'foregroundcolor','black',...
        'String','R2');

%Ec+
AlimentareEplus=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.4 0.18 0.05 0.05],...
    'backgroundcolor','#CDCDCD',... 
    'foregroundcolor','black',...
    'FontSize',12,...
    'String',num2str(Eplus),...
    'Callback','Eplus = str2num(get(AlimentareEplus,''String'')); afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);');
TextEp=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.35 0.175 0.05 0.05],...
    'FontSize',12,... 
    'backgroundcolor','#CDCDCD',... 
    'foregroundcolor','black',...
    'String','+Ec');

%Ec-
AlimentareEminus=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.4 0.1 0.05 0.05],...
    'FontSize',12,...
    'backgroundcolor','#CDCDCD',... 
    'foregroundcolor','black',...
    'String',num2str(Eminus),...
    'Callback','Eminus = str2num(get(AlimentareEminus,''String'')); afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);');
TextEcm=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.35 0.09 0.05 0.05],...
    'FontSize',12,... 
    'backgroundcolor','#CDCDCD',... 
    'foregroundcolor','black',...
    'String','-Ec');




afisare_semnal(A,f, Eplus, Eminus,tip,R1,R2);

